[workspace]

members = [
    "core",
    "dev-test",
    "lib/rklist",
    "lib/rkplat",
    "lib/rkboot",
    "lib/rkalloc",
    "lib/rkalloc_buddy",
    "lib/rkring",
    "lib/rkmbox",
    "lib/rksched",
    "lib/rkschedcoop",
    "lib/rkschedpreem",
    "lib/rksignal",
]
