[workspace]

members = [
    "core",
    "dev-test",
    "lib/rkplat",
    "lib/rkboot",
    "lib/rkalloc",
    "lib/rkalloc_buddy",
    "lib/rkring",
    "lib/rkmbox",
    "lib/rkblkdev",
    "lib/rksched"
]
